### PR TITLE
feat(drone): upgrade alpine to 3.9

### PR DESCRIPTION
**Pull request by appleboy**
Also remove renovate config.

### CODE REVIEW

**Comment by donny-dont** [comment]
Renovate would have figured this out if it were setup to actually match the things.

**Comment by donny-dont** [comment]
I don't think this should be merged. Instead we really should be using renovate to get the latest versions automatically.

**Comment by appleboy** [comment]
@donny-dont I followed the other PR like this https://github.com/drone-plugins/drone-download/pull/15 so remove the Renovate config.

**Comment by tboerger** [comment]
This is the only repo where I want to keep renovate. There is already a pr that explicitly defines the list of Dockerfiles

**Comment by appleboy** [comment]
@tboerger @tboerger restored

**Comment by tboerger** [comment]
Renovate works correctly now.

**Pull request closed without merging**
