### PR TITLE
Enable Windows 1909 build

### PR DESCRIPTION
**Pull request by donny-dont**
Add a Windows 1909 pipeline and remove the old .drone.yml file.

### CODE REVIEW

**Comment by techknowlogick** [comment]
Is there a 1909 runner available?

**Comment by donny-dont** [comment]
Yep I setup Golang on it and added the secret to this repo.

**Comment by donny-dont** [comment]
There's already images for it in drone https://hub.docker.com/layers/drone/drone-runner-docker/windows-1909-amd64/images/sha256-281ebcb80ebf2f8ebde6a7a9386fd8e4ff4afcf243f35972ae44e122fecdcb40?context=explore

**Review by techknowlogick — APPROVED** [review]

**Comment by donny-dont** [comment]
Thanks @techknowlogick !

**Pull request merged**
